version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: webtoon-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: webtoon_gallery
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - webtoon-network

volumes:
  mongo-data:
  mongo-config:

networks:
  webtoon-network:
    driver: bridge